### ISSUE TITLE
causes /help command and others to not work in servers, clients

### ISSUE THREAD

**Issue by Nick-77ab2** [Abastro/SciAPI#4]
I have this and stellar sky installed, just wondering if stellar sky's is a client only mod? if so i can take this down.
if not i'll post the report.

**Comment by Abastro** [comment]
No stellar sky is not client only mod.

**Comment by Nick-77ab2** [comment]
then shouldnt this be up still? it causes certain commands to not work when in a server

**Comment by Abastro** [comment]
I didn't have the same issue on any time.
First what version of SciAPI did you use? Also did you only have SciAPI on the test?

**Comment by Nick-77ab2** [comment]
sorry for not answering been busy lately, i have both sciAPI and the stellar sky in the server when this happens, at the time i was using the latest 1.9 of both. it still works with client even if i dont have it in the server.

**Comment by Abastro** [comment]
Yes, Stellar Sky does work as not only Client-Only but also Universal. So do not make issue here.
